# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=128)),
                ('like', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
