# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photos',
            table='photos',
        ),
    ]
